"""add response cache

Revision ID: 18aa3c193394
Revises: 73f76217816f
Create Date: 2026-10-05 23:21:43.872619

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18aa3c193394'
down_revision: str | None = '73f76217816f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response_cache',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('response_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_response_cache_cache_key'), ['cache_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_response_cache_expires_at'), ['expires_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_response_cache_expires_at'))
        batch_op.drop_index(batch_op.f('ix_response_cache_cache_key'))

    op.drop_table('response_cache')
    # ### end Alembic commands ###
