"""initial schema

Revision ID: 73f76217816f
Revises: 
Create Date: 2026-10-05 23:10:55.237906

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73f76217816f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_normalized', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('claimed_location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_name_normalized'), ['name_normalized'], unique=False)

    op.create_table('domains',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('tld', sa.String(length=32), nullable=True),
    sa.Column('age_days', sa.Integer(), nullable=True),
    sa.Column('registration_date', sa.String(length=64), nullable=True),
    sa.Column('registrar', sa.String(length=255), nullable=True),
    sa.Column('https_enabled', sa.Boolean(), nullable=True),
    sa.Column('dns_resolves', sa.Boolean(), nullable=True),
    sa.Column('company_name_match', sa.Boolean(), nullable=True),
    sa.Column('cheap_tld', sa.Boolean(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domains_domain'), ['domain'], unique=True)

    op.create_table('opportunities',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('salary', sa.String(length=128), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('duration', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunities_company_id'), ['company_id'], unique=False)

    op.create_table('investigations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=True),
    sa.Column('opportunity_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('raw_input', sa.Text(), nullable=False),
    sa.Column('user_input', sa.JSON(), nullable=False),
    sa.Column('investigation', sa.JSON(), nullable=False),
    sa.Column('risk', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investigations_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investigations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_investigations_opportunity_id'), ['opportunity_id'], unique=False)

    op.create_table('user_reports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=True),
    sa.Column('opportunity_id', sa.String(length=32), nullable=True),
    sa.Column('report_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_reports_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_reports_created_at'), ['created_at'], unique=False)

    op.create_table('detected_patterns',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('investigation_id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=True),
    sa.Column('pattern_type', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detected_patterns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detected_patterns_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detected_patterns_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detected_patterns_pattern_type'), ['pattern_type'], unique=False)

    op.create_table('risk_assessments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('investigation_id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_assessments_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_assessments_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_assessments_level'), ['level'], unique=False)

    op.create_table('web_evidence',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('investigation_id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('source_domain', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('content_summary', sa.Text(), nullable=False),
    sa.Column('evidence_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('web_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_web_evidence_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_web_evidence_investigation_id'), ['investigation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_web_evidence_investigation_id'))
        batch_op.drop_index(batch_op.f('ix_web_evidence_company_id'))

    op.drop_table('web_evidence')
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_assessments_level'))
        batch_op.drop_index(batch_op.f('ix_risk_assessments_investigation_id'))
        batch_op.drop_index(batch_op.f('ix_risk_assessments_company_id'))

    op.drop_table('risk_assessments')
    with op.batch_alter_table('detected_patterns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detected_patterns_pattern_type'))
        batch_op.drop_index(batch_op.f('ix_detected_patterns_investigation_id'))
        batch_op.drop_index(batch_op.f('ix_detected_patterns_company_id'))

    op.drop_table('detected_patterns')
    with op.batch_alter_table('user_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_reports_created_at'))
        batch_op.drop_index(batch_op.f('ix_user_reports_company_id'))

    op.drop_table('user_reports')
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investigations_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_investigations_created_at'))
        batch_op.drop_index(batch_op.f('ix_investigations_company_id'))

    op.drop_table('investigations')
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunities_company_id'))

    op.drop_table('opportunities')
    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domains_domain'))

    op.drop_table('domains')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_name_normalized'))
        batch_op.drop_index(batch_op.f('ix_companies_name'))

    op.drop_table('companies')
    # ### end Alembic commands ###
